--empresas
CREATE TABLE IF NOT EXISTS "empresas"();
ALTER TABLE "empresas" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "empresas" ADD COLUMN IF NOT EXISTS "razaoSocial" VARCHAR(100);
ALTER TABLE "empresas" ADD COLUMN IF NOT EXISTS "nomeFantasia" VARCHAR(100);
ALTER TABLE "empresas" ADD COLUMN IF NOT EXISTS "cpfCnpj" VARCHAR(14);

--usuarios
CREATE TABLE IF NOT EXISTS "usuarios"();
ALTER TABLE "usuarios" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "usuarios" ADD COLUMN IF NOT EXISTS "email" VARCHAR(100);
ALTER TABLE "usuarios" ADD COLUMN IF NOT EXISTS "nome" VARCHAR(80);