--empresas
CREATE TABLE IF NOT EXISTS "empresas"();
ALTER TABLE "empresas" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "empresas" ADD COLUMN IF NOT EXISTS "razaoSocial" VARCHAR(100);
ALTER TABLE "empresas" ADD COLUMN IF NOT EXISTS "nomeFantasia" VARCHAR(100);
ALTER TABLE "empresas" ADD COLUMN IF NOT EXISTS "cpfCnpj" VARCHAR(14);

--usuarios
CREATE TABLE IF NOT EXISTS "usuarios"();
ALTER TABLE "usuarios" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "usuarios" ADD COLUMN IF NOT EXISTS "email" VARCHAR(100);
ALTER TABLE "usuarios" ADD COLUMN IF NOT EXISTS "nome" VARCHAR(80);

--parceiros
CREATE TABLE IF NOT EXISTS "parceiros"();
ALTER TABLE "parceiros" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "parceiros" ADD COLUMN IF NOT EXISTS "isCliente" BOOLEAN;
ALTER TABLE "parceiros" ADD COLUMN IF NOT EXISTS "isFornecedor" BOOLEAN;
ALTER TABLE "parceiros" ADD COLUMN IF NOT EXISTS "isTransportadora" BOOLEAN;
ALTER TABLE "parceiros" ADD COLUMN IF NOT EXISTS "isFuncionario" BOOLEAN;
ALTER TABLE "parceiros" ADD COLUMN IF NOT EXISTS "cpfCnpj" VARCHAR(14);
ALTER TABLE "parceiros" ADD COLUMN IF NOT EXISTS "nome" VARCHAR(100);
ALTER TABLE "parceiros" ADD COLUMN IF NOT EXISTS "apelido" VARCHAR(100);
ALTER TABLE "parceiros" ADD COLUMN IF NOT EXISTS "nascimento" DATE;
ALTER TABLE "parceiros" ADD COLUMN IF NOT EXISTS "sexo" SMALLINT;
ALTER TABLE "parceiros" ADD COLUMN IF NOT EXISTS "estadoCivil" SMALLINT;
ALTER TABLE "parceiros" ADD COLUMN IF NOT EXISTS "rg" VARCHAR(20);
ALTER TABLE "parceiros" ADD COLUMN IF NOT EXISTS "ie" VARCHAR(30);
ALTER TABLE "parceiros" ADD COLUMN IF NOT EXISTS "im" VARCHAR(30);
ALTER TABLE "parceiros" ADD COLUMN IF NOT EXISTS "escolaridade" SMALLINT;
ALTER TABLE "parceiros" ADD COLUMN IF NOT EXISTS "profissao" VARCHAR(80);
ALTER TABLE "parceiros" ADD COLUMN IF NOT EXISTS "tabelaPrecoId" UUID;
ALTER TABLE "parceiros" ADD COLUMN IF NOT EXISTS "isAtivo" BOOLEAN DEFAULT true;
ALTER TABLE "parceiros" ADD COLUMN IF NOT EXISTS "isBloquearVenda" BOOLEAN DEFAULT false;
ALTER TABLE "parceiros" ADD COLUMN IF NOT EXISTS "isBloquearCompra" BOOLEAN DEFAULT false;

--parceirosContato
CREATE TABLE IF NOT EXISTS "parceirosContato"();
ALTER TABLE "parceirosContato" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "parceirosContato" ADD COLUMN IF NOT EXISTS "parceiroId" UUID;
ALTER TABLE "parceirosContato" ADD COLUMN IF NOT EXISTS "nome" VARCHAR(80);
ALTER TABLE "parceirosContato" ADD COLUMN IF NOT EXISTS "telefone" VARCHAR(30);
ALTER TABLE "parceirosContato" ADD COLUMN IF NOT EXISTS "email" VARCHAR(120);

--parceirosEndereco
CREATE TABLE IF NOT EXISTS "parceirosEndereco"();
ALTER TABLE "parceirosEndereco" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "parceirosEndereco" ADD COLUMN IF NOT EXISTS "parceiroId" UUID;
ALTER TABLE "parceirosEndereco" ADD COLUMN IF NOT EXISTS "cep" VARCHAR(8);
ALTER TABLE "parceirosEndereco" ADD COLUMN IF NOT EXISTS "logradouro" VARCHAR(100);
ALTER TABLE "parceirosEndereco" ADD COLUMN IF NOT EXISTS "numero" VARCHAR(20);
ALTER TABLE "parceirosEndereco" ADD COLUMN IF NOT EXISTS "complemento" VARCHAR(50);
ALTER TABLE "parceirosEndereco" ADD COLUMN IF NOT EXISTS "bairro" VARCHAR(50);
ALTER TABLE "parceirosEndereco" ADD COLUMN IF NOT EXISTS "estadoId" UUID;

--estados
CREATE TABLE IF NOT EXISTS "estados"();
ALTER TABLE "estados" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "estados" ADD COLUMN IF NOT EXISTS "nome" VARCHAR(60);
ALTER TABLE "estados" ADD COLUMN IF NOT EXISTS "uf" VARCHAR(2);
ALTER TABLE "estados" ADD COLUMN IF NOT EXISTS "ibge" INT;
ALTER TABLE "estados" ADD COLUMN IF NOT EXISTS "pais" INT;
ALTER TABLE "estados" ADD COLUMN IF NOT EXISTS "ddd" JSON;

--produtos
CREATE TABLE IF NOT EXISTS "produtos"();
ALTER TABLE "produtos" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "produtos" ADD COLUMN IF NOT EXISTS "descricao" VARCHAR(100);

--servicos
CREATE TABLE IF NOT EXISTS "servicos"();
ALTER TABLE "servicos" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "servicos" ADD COLUMN IF NOT EXISTS "descricao" VARCHAR(100);

--tabelasPreco
CREATE TABLE IF NOT EXISTS "contratos"();
ALTER TABLE "contratos" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "contratos" ADD COLUMN IF NOT EXISTS "clienteId" UUID;
ALTER TABLE "contratos" ADD COLUMN IF NOT EXISTS "inicio" DATE;
ALTER TABLE "contratos" ADD COLUMN IF NOT EXISTS "termino" DATE;
ALTER TABLE "contratos" ADD COLUMN IF NOT EXISTS "isCancelado" BOOLEAN DEFAULT false;

--tabelasPreco
CREATE TABLE IF NOT EXISTS "tabelasPreco"();
ALTER TABLE "tabelasPreco" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "tabelasPreco" ADD COLUMN IF NOT EXISTS "descricao" VARCHAR(100);